name: Facebook Automation

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright
        run: |
          pip install playwright
          playwright install chromium --with-deps

      - name: Run Facebook Script
        env:
          TZ: "Asia/Karachi"
        run: python main.py

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: facebook-results
          path: |
            facebook_profile.png
            facebook_cookies.txt
          retention-days: 7
